version: "3"

services:
  frontend:
    build:
      context: ./frontend  # Path to the directory containing the frontend Dockerfile
    ports:
      - "3000:3000"  # Map container port 80 to host port 80
    environment:
      - REACT_APP_BASE_URL=http://localhost:3030  # Assuming the backend service is named "backend"
    depends_on:
      - backend  # Expresses a dependency on the "backend" service

  backend:
    build:
      context: ./backend  # Path to the directory containing the backend Dockerfile
    ports:
      - "3030:3030"  # Map container port 3030 to host port 3030
    
networks:
  default:
    external:
      name: short-url
